name: Node Microservice CI-CD

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: node-microservice
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

# ---------- STAGE 1: CHECKOUT ----------
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


# ---------- STAGE 2: INSTALL ----------
  install:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install


# ---------- STAGE 3: DOCKER BUILD ----------
  docker-build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .


# ---------- STAGE 4: DOCKER PUSH ----------
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest


# ---------- STAGE 5: SECURITY SCAN ----------
  trivy-scan:
    runs-on: ubuntu-latest
    needs: docker-push

    steps:
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/node-microservice:latest
          severity: HIGH,CRITICAL
          exit-code: 0
