name: Node Microservice CI-CD (Stage Based)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: node-microservice
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

# -------------------- STAGE 1 --------------------
  checkout:
    name: Stage 1 - Checkout Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


# -------------------- STAGE 2 --------------------
  install:
    name: Stage 2 - Install Dependencies
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies using lock file
        run: npm ci


# -------------------- STAGE 3 --------------------
  docker-build:
    name: Stage 3 - Docker Build
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .


# -------------------- STAGE 4 --------------------
  docker-push:
    name: Stage 4 - Docker Push
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest


# -------------------- STAGE 5 --------------------
  trivy-scan:
    name: Stage 5 - Trivy Security Scan
    runs-on: ubuntu-latest
    needs: docker-push

    steps:
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/node-microservice:latest
          severity: HIGH,CRITICAL
          exit-code: 0
