name: NodeJS CI-CD (Docker + Trivy)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: node-microservice
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

    - name: Push Docker Image
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

    - name: Trivy Scan (LATEST)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/node-microservice:latest
        severity: HIGH,CRITICAL
        exit-code: 1
        scanners: vuln
      env:
        TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
